print ('                                    ***LOS PARAMETROS SEP Y END***                           ')
print ('La funcion print (), es quizas una de las herramientas mas utiles en el lenguaje de programacion Python', end=' ')
print (', al momento de interactuar con los usuarios de nuestros programas.', end =' ')
print ('Por tal motivo, es indispensable conocer la manera en que podemos manipular dichas impresiones', end = ' ')
print ('en pantalla, con la finalidad de tener el control completo del texto a mostrar y para ello', end = ' ')
print ('contamos con el parametro sep y end.', end = ' ')
print ('EL PARAMETRO END, se utiliza para agregar cualquier cadena de caracteres al final de la salida e', end =' ')
print ('imporesion en pantalla de la funcion print(). Ademas, por defecto la funcion print () genera un', end = ' ')
print ('salto de linea al terminar su ejecucion, sin embargo, con aydua del parametro END, es posible', end = ' ')
print ('evitar este salto de linea.')
print ('Esto es un', end = ' ')
print ('ejemplo')
print ('*PARAMETRO SEP*')
print ('En ocasiones, es posible que deseemos imprimir valores de manera legible utilizando la funcion', end=' ')
print ('print () para ello contamos con el parametro SEP. El parametro SEP, se utiliza para dar formato', end=' ')
print ('a las cadenas de caracteres que deben imprimirse en pantalla, agregando un separador entre', end= ' ')
print ('las cadenas que se imprimiran')
print ('1','2','3','4','5', sep = '-' )
